# Copyright (c) 2024, Shanghai Iluvatar CoreX Semiconductor Co., Ltd.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "ix-exporter"
  labels:
    app.kubernetes.io/name: "ix-exporter"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "ix-exporter"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "ix-exporter"
      name: "ix-exporter"
    spec:
      containers:
      - image: "iluvatarcorex/ix-exporter:3.1.1"
        name: "ix-exporter"
        ports:
        - name: "metrics"
          containerPort: 32021
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: "pod-resources"
          readOnly: true
          mountPath: "/var/lib/kubelet/pod-resources"
      volumes:
      - name: "pod-resources"
        hostPath:
          path: "/var/lib/kubelet/pod-resources"

---

kind: Service
apiVersion: v1
metadata:
  name: "ix-exporter"
  labels:
    app.kubernetes.io/name: "ix-exporter"
spec:
  selector:
    app.kubernetes.io/name: "ix-exporter"
  ports:
  - name: "metrics"
    port: 32021
