# Copyright (c) 2024, Shanghai Iluvatar CoreX Semiconductor Co., Ltd.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
      name: {{ .Release.Name }}
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      priorityClassName: system-node-critical
      serviceAccountName: service-account-{{ .Release.Name }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: {{ .Release.Name }}
          args:
            - --log-level={{ .Values.daemonset.logLevel }}
            - --ip={{ .Values.service.ip }}
            - --enable-kubernetes=true
            - --resource-name={{ .Values.daemonset.resourceName }}
          securityContext:
            privileged: true
            runAsNonRoot: false
            runAsUser: 0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: "metrics"
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: pod-resources
              readOnly: true
              mountPath: "/var/lib/kubelet/pod-resources"
            - name: host-proc
              mountPath: /host-proc
              readOnly: true
              mountPropagation: HostToContainer
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /dev
              name: dev
            - name: log-dir
              mountPath: "/var/log/iluvatarcorex"
              readOnly: false
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 45
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 45
      volumes:
        - name: host-proc
          hostPath:
            path: "/proc"
        - name: pod-resources
          hostPath:
            path: "/var/lib/kubelet/pod-resources"
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev
        - name: log-dir
          hostPath:
            path: "/var/log/iluvatarcorex"
            type: DirectoryOrCreate
