# Default values for ix-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: "ix-exporter:4.2.0-x86_64" # Replace it with your image address.

daemonset:
  logLevel: "4" # Set the log level (0-6), 0-panic, 1-fatal, 2-error, 3-warn, 4-info, 5-debug, 6-trace, defalut is 4.
  logFile: "/tmp/log/ix-exporter.log"

service:
  ip: "0.0.0.0" # The service ip to provide metrics
  port: "32021" # The service port to provide metrics

serviceMonitor: 
  enabled: false # Set to true to enable the creation of a ServiceMonitor
  namespace: "monitoring" # The namespace where the ServiceMonitor will be created
  interval: 30s
  honorLabels: false # Controls whether Prometheus preserves the metric's labels when they collide with the target's labels.
  honorTimestamps: false # Controls whether Prometheus preserves the timestamps when exposed by the target.

nodeSelector: {}
  #node: gpu

tolerations: []
#- operator: Exists

affinity: {}
  #nodeAffinity:
  #  requiredDuringSchedulingIgnoredDuringExecution:
  #    nodeSelectorTerms:
  #    - matchExpressions:
  #      - key: iluvatar-gpu
  #        operator: Exists